### ISSUE TITLE
0xLogos - AsyncSynthVault using wrong callback interface

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-amphor-judging#122]
0xLogos

medium

# AsyncSynthVault using wrong callback interface

## Summary

AsyncSynthVault not complilant with ERC7540 callbacks.

## Vulnerability Detail

In ERC [specification](https://eips.ethereum.org/EIPS/eip-7540#request-callbacks) interface for callback function is:
```yaml
- name: onERC7540DepositReceived
  type: function

  inputs:
    - name: operator
      type: address
    - name: owner
      type: address
    - name: requestId
      type: uint256
    - name: assets
      type: uint256
    - name: data
      type: bytes
  outputs:
    - name: interfaceId
      type: bytes4
```

But in AsyncSynthVault contract implementation `assets` parameter is missed:
```solidity
if (
    data.length > 0 && 
    ERC7540Receiver(receiver).onERC7540DepositReceived(
        _msgSender(), owner, epochId, data
    ) != ERC7540Receiver.onERC7540DepositReceived.selector
) revert ReceiverFailed();
```
Same for `onERC7540RedeemReceived`.

## Impact

AsyncSynthVault not complilant with ERC7540 callbacks. Any ERC7540 integrations will be broken.

## Code Snippet

https://github.com/sherlock-audit/2024-03-amphor/blob/6c797025ffe296e04607abf74400ff2bb36a7de3/asynchronous-vault/src/AsyncSynthVault.sol#L711C1-L716C35

https://github.com/sherlock-audit/2024-03-amphor/blob/6c797025ffe296e04607abf74400ff2bb36a7de3/asynchronous-vault/src/AsyncSynthVault.sol#L732-L737

## Tool used

Manual Review

## Recommendation

Add `assets` parameter and ensure that implementation and specification selectors match.
